import { view as view0, logicFunc as logic0 } from './views/view0.js';
import { view as view1, logicFunc as logic1 } from './views/view1.js';
import { view as view2, logicFunc as logic2 } from './views/view2.js';
import { view as view3, logicFunc as logic3 } from './views/view3.js';
import { view as view4, logicFunc as logic4 } from './views/view4.js';
import { view as view5, logicFunc as logic5 } from './views/view5.js';
import { view as view6, logicFunc as logic6 } from './views/view6.js';
import { view as view7, logicFunc as logic7 } from './views/view7.js';
import { view as view8, logicFunc as logic8 } from './views/view8.js';
import { view as view9, logicFunc as logic9 } from './views/view9.js';
import { view as view10, logicFunc as logic10 } from './views/view10.js';
import { view as view11, logicFunc as logic11 } from './views/view11.js';
import { view as view12, logicFunc as logic12 } from './views/view12.js';
import { view as view13, logicFunc as logic13 } from './views/view13.js';
import { view as view14, logicFunc as logic14 } from './views/view14.js';
import { view as view15, logicFunc as logic15 } from './views/view15.js';
import { view as view16, logicFunc as logic16 } from './views/view16.js';
import { view as view17, logicFunc as logic17 } from './views/view17.js';
import { view as view18, logicFunc as logic18 } from './views/view18.js';
import { view as view19, logicFunc as logic19 } from './views/view19.js';
import { view as view20, logicFunc as logic20 } from './views/view20.js';
import { view as view21, logicFunc as logic21 } from './views/view21.js';
import { view as view22, logicFunc as logic22 } from './views/view22.js';
import { view as view23, logicFunc as logic23 } from './views/view23.js';
import { view as view24, logicFunc as logic24 } from './views/view24.js';

export const views = [view0, view1, view2, view3, view4, view5, view6, view7, view8, view9, view10, view11, view12, view13, view14, view15, view16, view17, view18, view19, view20, view21, view22, view23, view24];
export const logics = [logic0, logic1, logic2, logic3, logic4, logic5, logic6, logic7, logic8, logic9, logic10, logic11, logic12, logic13, logic14,logic15,logic16,logic17,logic18,logic19,logic20,logic21,logic22,logic23,logic24];